### PR TITLE
Objective-C support

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Looks good @ricardopereira :)

Worth having a few high level tests perhaps from Obj-C to prove interoperability firstly, but also to ensure there are no regressions?  I expect this can be done easily with some very high level tests just checking that the interface works as expected.

**Comment by tidwall** [comment]
@ricardopereira Very cool! I did a cursory review and I don't see anything alarming. l'll poke around a bit and test it in some of my projects.

**Comment by tidwall** [comment]
It passes all the Autobahn tests and runs fine in swift as far as I can tell. I haven't tested it with objective-c yet. At this point we should probably have a simple unit test specifically for objective-c that binds all the delegate methods. Ideally connecting to an echo service similar to the example code in the Readme.

**Comment by ricardopereira** [comment]
@mattheworiordan @tidwall Tests done #20.

**Pull request merged**
