### PR TITLE
Objective-C integration tests

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by ricardopereira** [comment]
Run the test with `./tools/run-objc-test.sh`.

**Comment by ricardopereira** [comment]
I created a new test target `Test-ObjectiveC` and if it compiles then it is all good.

**Comment by tidwall** [comment]
Yep. It compiles.

**Comment by mattheworiordan** [comment]
Great work @ricardopereira.

@tidwall and @ricardopereira, out of interest, how does the test suite get run automatically i.e. I see the Authobahn test results at https://tidwall.github.io/SwiftWebSocket/results/, is this tested on each commit, and if so, is there any way to ensure the Obj-C tests run as well? @tidwall we are integrating this library into our own client library https://github.com/ably/ably-ios, and as such, I would like to ensure that we can continue to keep up to date with your library.  If a regression is introduced in future, and the test suite is not automatically run, then I fear whoever introduces the regression would never know until someone else discovers it when using the library's Obj-C interface.  Any thoughts?

**Comment by tidwall** [comment]
The Autobahn test is very thorough takes around 10 minutes to run. It's executed on the local machine prior to any commit to master. You can find the test at `./Test/Autobahn/run.sh`. A report will get dumped to subdirectory. This test is not automatic. Even though I'm pretty strict about running it often and before each commit, it's all in all possible that in a stupor I could forget to run the test and a regression could occur. The Obj-C test runs when the Cocoapod is generated.

I should note that it may be possible to webhook the project commits to TravisCI or CircleCI. I've tried these services over 6 months ago. At the time both service had difficultly running the Autobahn test. From what I remember, CircleCI was still looking into Xcode 7 support, and TravisCI couldn't run the `swift` command. 

I recognize this is an issue and added it to Github. #21

Releases are tagged following the [Semantic Versioning](http://semver.org/) rules. If you plan on using SwiftWebSocket in your production app then I recommend that you use Cocoapods or Carthage. Also I recommend pointing to tagged releases, not master or dev. 

I'll re-investigate an automated test hook that will suffice for your project before the next tagged release. And thanks a ton @ricardopereira for your quality PR.

**Comment by mattheworiordan** [comment]
@tidwall makes sense, thanks for the thorough response.  And great library, thanks!

**Pull request merged**
