### PR TITLE
Fixes for Xcode 7 beta 6

### PR DESCRIPTION
**Pull request by marcboeker**
Sorry for producing some noise in the diff, but my editor automatically removes whitespaces in blank lines.

### CODE REVIEW

**Comment by tidwall** [comment]
Which editor do you use?

**Comment by marcboeker** [comment]
Atom, but I've configured Sublime to do the same. I've tested the changes in Xcode, but was to lazy to clone and edit my fork in Xcode, so I've used Atome for the quick edit.

**Comment by tidwall** [comment]
I just ran a test and the pull request is failing at line 622.

```
error: '[String]' does not have a member named 'joinWithSeparator'
            req.setValue(subProtocols.joinWithSeparator(";"), forHTTPHeaderField: "Sec-WebSocket-Protocol")
```

I'm not sure that `joinWithSeperator` is a Swift function.

**Comment by marcboeker** [comment]
Swift has changed this in the last Xcode beta release. Alamofire has made the same changes to work with Xcode 7 beta 6. Please see:

https://github.com/Alamofire/Alamofire/commit/6ad672cc5e16240de7c7005ce1a430a0233b9575

**Comment by tidwall** [comment]
Looks good. Thanks!

**Comment by marcboeker** [comment]
Thanks!

**Pull request merged**
