### PR TITLE
Swift 5 migration. Warnings fixed.

### PR DESCRIPTION
**Pull request by starxor**

### CODE REVIEW

**Comment by T2SoftDev** [comment]
@tidwall any idea when you can merge this?

**Comment by lazerwalker** [comment]
+1, would love to see this hit master sooner rather than later.

**Comment by tidwall** [comment]
Thanks for the PR!

**Comment by pickettjd** [comment]
@tidwall Can you update the podspec?

**Comment by raza08** [comment]
@tidwall @pickettjd How can I use it in my pod file?

**Comment by wiistriker** [comment]
just replace dep in your Podfile:
pod 'SwiftWebSocket', :git => 'https://github.com/tidwall/SwiftWebSocket.git', :tag => 'v2.8.0'

**Pull request merged**
